### ISSUE TITLE
implement binary search in C

### ISSUE THREAD

**Issue by Khizarshah01** [Khizarshah01/DataStructure-DSA-#1]
add binary search c program on Binary_search directory

**Comment by MDK8888** [comment]
Hey, I'd love to work on this!

**Comment by Khizarshah01** [comment]
@MDK8888 i assigned you this work hope you can do this work.

**Comment by Khizarshah01** [comment]
@MDK8888 Bro your concept is right. but in program main function is missing so the program giving error. please correct it and make program like a user can give a input.
