### ISSUE TITLE
Implement Queue using linked list

### ISSUE THREAD

**Issue by Khizarshah01** [Khizarshah01/DataStructure-DSA-#2]
Implement Queue using linked list in C. Add program on Queue directory

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Khizarshah01** [comment]
@tarunsamanta2k20 i assigned you this work hope you can do this work.

**Comment by Khizarshah01** [comment]
good job bro! but i said that implement queue in c programming language.

**Comment by tarunsamanta2k20** [comment]
Change the file extension to .c instead of .cpp
